name: App
options:
  bundleIdPrefix: com.objp.app
  deploymentTarget:
    iOS: 17
settings:
  base:
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: 1.0.0

packages:
  ios:
    path: ..

targets:
  App:
    settings:
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
    type: application
    platform: iOS
    sources: [Sources]
    dependencies:
      - package: ios
        product: Previews
